### ISSUE TITLE
ArgumentsSpacing Exception isn't working

### ISSUE THREAD

**Issue by badmacstone** [dsheiko/jscodesniffer#18]
Hi there,

I'm trying to use my own coding-standard but the exceptions of ArgumentsSpacing and ParametersSpacing aren't working. Here ´'s the rule:

```
"ArgumentsSpacing": {
		"allowArgPrecedingWhitespaces": 1,
		"allowArgTrailingWhitespaces": 0,
		"exceptions": {
			"singleArg": {
				"for": [ "FunctionExpression", "ArrayExpression", "ObjectExpression" ],
				"allowArgPrecedingWhitespaces": 0,
				"allowArgTrailingWhitespaces": 0
			},
			"firstArg": {
				"for": [ "FunctionExpression", "ArrayExpression", "ObjectExpression" ],
				"allowArgPrecedingWhitespaces": 0
			},
			"lastArg": {
				"for": [ "FunctionExpression", "ArrayExpression", "ObjectExpression" ],
				"allowArgTrailingWhitespaces": 0
			}
		}
	}
```
And this line creates following error:
```
$(selector).css("width", final + "px");
```
```
ArgumentsSpacing: There must be one whitespace(s) preceding argument; no found
```

What I want is: 1 whitespace between every argument. But not before the first argument and not after the last argument. That implies no whitespaces before and after a single argument too.

Thanks for help!

**Comment by tersmitten** [comment]
+1 for the "1 whitespace between every argument. But not before the first argument and not after the last argument"

**Comment by dsheiko** [comment]
Check in the rule set you provide - you specify explicitly what nodes you mean for the exceptions:
```
"for": [ "FunctionExpression", "ArrayExpression", "ObjectExpression" ]
```
Arguments of your example o not match any of these:
```
$(selector).css("width", final + "px");
```
`selector` is Identifier
`"width"` - Literal
`final + "px"` - BinaryExpression

By http://esprima.org/demo/parse.html

I've just deployed jscodesniffer 2.1.14 where you can simply omit "for" 

```
 "ArgumentsSpacing": {
        "allowArgPrecedingWhitespaces": 1,
        "allowArgTrailingWhitespaces": 0,
        "exceptions": {
            "singleArg": {
                "allowArgPrecedingWhitespaces": 0,
                "allowArgTrailingWhitespaces": 0
            },
            "firstArg": {
                "allowArgPrecedingWhitespaces": 0
            },
            "lastArg": {
                "allowArgTrailingWhitespaces": 0
            }
        }
      }
```

See my test 
https://github.com/dsheiko/jscodesniffer/blob/master/test/try.js
```
 mocha test/try.js
```
