### ISSUE TITLE
Wrong EmptyConstructsSpacing validation 

### ISSUE THREAD

**Issue by FnTm** [dsheiko/jscodesniffer#25]
I've got a little piece of code that is failing validation, and I can't figure out why that is. I suspect a bug.

The code I'm using is as follows:
```js
if (typeof piwikDomain != "undefined") {
    var _paq = _paq || [];
    (function(){
    var piwikDomain = true;
    })();
}
else {
    console.warn( "piwikDomain variable not defined" );
}
```

I have been testing this with both node-jscs and the [online validator](http://dsheiko.github.io/jscodesniffer/), and in both cases I get this: 
`3	4	There must be no whitespaces in empty constructs; one found`

Does this qualify as a bug, or do I really have some sort of error in my syntax that I am not aware of?

**Comment by dsheiko** [comment]
just deployed rev. 2.2.2 with the fix. Do:
```
sudo npm i jscodesniffer -g
```

This code goes without validation errors to me now:
```javascript
if ( typeof piwikDomain !== "undefined" ) {
	var _paq = _paq || [];
	(function(){
		var piwikDomain = true;
	})();
}
else {
	console.warn( "piwikDomain variable not defined" );
}
```
